# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /posts/:year/:title

# Setup
title:            Hoburg Research Group
description:      "part of the Department of Aeronautics and Astronautics at MIT"
url:              http://hoburg.mit.edu
baseurl:

paginate:         5
paginate_path: "/posts/:num"

roles:
    - {key: Principal Investigator, name: Principal Investigator, display: short}
    - {key: Doctoral Student, name: Doctoral Students, display: short}
    - {key: Master's Student, name: Master's Students, display: short}
    - {key: Undergraduate Researcher, name: Undergraduate Researchers, display: short}
    - {key: Alumnus, name: Alumni, display: short}
